name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        working-directory: ${{ github.workspace }} # Correção definitiva!
        run: npm ci
      - name: Install Angular CLI (local)
        working-directory: ${{ github.workspace }} # Correção definitiva!
        run: npm install
      - name: Build Angular App
        working-directory: ${{ github.workspace }} # Correção definitiva!
        run: npx ng build
      - name: Run Tests
        working-directory: ${{ github.workspace }} # Correção definitiva!
        run: npx ng test --watch=false --browsers=ChromeHeadless
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/app # Caminho correto dentro do dist (sem o nome do projeto na frente)
