name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Angular App
        run: ng build
      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/app # MUITO IMPORTANTE: VERIFIQUE O NOME DA PASTA AQUI!
