name: Test Secrets

on:
  push:
    branches: [master]

jobs:
  test_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode JSON Secret and Extract Project ID
        id: extract_project_id
        shell: bash
        run: |
          SECRET_JSON=$(echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPFRENCH_A0C06 }}")
          PROJECT_ID=$(echo "$SECRET_JSON" | jq -r '.project_id')
          echo "::set-output name=project_id::$PROJECT_ID"

      - name: Print Project ID
        run: echo "${{ steps.extract_project_id.outputs.project_id }}"

      - name: Print Secret Value (Masked - For Verification Only)
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPFRENCH_A0C06 }}"
